language: go
go:
  - 1.6

services:
  - docker

os:
  - linux
  - osx

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - IMAGE=cardigann/cardigann
    - IMAGE_VERSION=$IMAGE:$COMMIT
    - secure: "zjEZNMyeuXcWA4o0bGl/fLIznrMOtXKX7OzbnGmng+1E/onRZeG+Wd7QqB0aPOk+oHDpn4/Kdh6x6exxrKVeIKK3Ud7tgss1GtpC8MNhZnvIQCJ4wfRmXb+Nb8HSJymNDgrdpEpbE5egawLp4x7qzfD9FiJxeldbiRllkixVMkVU9ERKO52XYcQQ54WN6iwr2grMIvdyyfzlnWG0WSdFrpCwpfnB2iL9HErNIXyrDqtHKDVFhnR3moR2x+GsWHNeBVm9oStwKFDY84lUy7tCeaxLd7+M+Zwu7izSnsayXu8sAWmM3hwXSOduCkA0RcBYhyNMvQ+2iDXcGUsBkemuJ35g0QZEvHzaD/Mv7EpHT0d6UcCiNSZj8EFXF4FZYZDbs0kwE4bjLH1PKYe6nRPhtv6shd+RXu8A5zArWzkyAh97BgSHn+obxj+vEr8uTyRrUwG0tPzsSOXz1usphqES+PXvV1KXtwuNNjLJElZcn5fLWb5Rrfcc+9TZA5dH15SyfY4eyZGtrBhAYG75/l2Pz0u8YOQE3lMWdKsy3BTSSlvIo6x1KlKBKKMI2GFbpbxWdISWnxbhkBa7CqLnjKDuR2mmobh/bib9WqgXEfVnWswKgkbqYMvU+Ey/rZhmQQJQXOAa8jbi401trIY1LkhB93jlePVMtgXvoozmhUzvzEM="

script:
  - make test

before_deploy:
  - make build-without-static
  - ./cardigann version
  - docker build --build-arg BIN=./cardigann -t ${IMAGE}:${COMMIT} .
  - docker tag ${IMAGE}:${COMMIT} ${IMAGE}:latest
  - docker tag ${IMAGE}:${COMMIT} ${IMAGE}:travis-${TRAVIS_BUILD_NUMBER}
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"

deploy:
  skip_cleanup: true
  provider: script
  script: docker push ${IMAGE}
  on:
    branch:
      - master
      - travis-docker-builds
    condition: $TRAVIS_OS_NAME = linux
