version: "2"

services:
  cardigann:
    build: .
    volumes:
      - ./config.json:/.config/cardigann/config.json
    environment:
      - CARDIGANN_PASSPHRASE
      - CARDIGANN_HOSTNAME=cardigann
    command: ["server", "--debug"]
    ports:
    - 5060:5060

  couchpotato:
    image: linuxserver/couchpotato
    environment:
      - ADVANCED_DISABLEUPDATES=1
      - PUID=0
      - PGID=0
    depends_on:
      - cardigann
    ports:
      - 5050:5050

  sonarr:
    image: linuxserver/sonarr
    environment:
      - ADVANCED_DISABLEUPDATES=1
      - PUID=0
      - PGID=0
    depends_on:
      - cardigann
    ports:
      - 8989:8989

  radarr:
    image: linuxserver/radarr
    environment:
      - ADVANCED_DISABLEUPDATES=1
      - PUID=0
      - PGID=0
    depends_on:
      - cardigann
    ports:
      - 7878:7878

